#! /bin/bash

curl -XDELETE http://127.0.0.1:9200/browserify-search/
curl -XPUT http://127.0.0.1:9200/browserify-search/ -d '
{
  "mappings": {
    "module": {
      "properties": {
        "browserifiability": {
          "type": "float"
        },
        "downloadsLastMonth": {
          "properties": {
            "start": {
              "type": "string"
            },
            "count": {
              "type": "long"
            },
            "cdf": {
              "type": "float"
            }
          }
        },
        "search": {
          "properties": {
            "description": {
              "type": "string",
              "boost": 1.2
            },
            "keywords": {
              "type": "string",
              "boost": 1.2
            },
            "name": {
              "type": "string",
              "boost": 1.4
            },
            "readme": {
              "type": "string",
              "boost": 0.5
            }
          }
        },
        "author": {
          "type": "string",
          "index": "not_analyzed"
        },
        "github": {
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}'